### ISSUE TITLE
where is the Android and iOS core code file?

### ISSUE THREAD

**Issue by Web3TomCat** [biill/StackthonProject#1]
first,thank your project! I want to run this project,but i can not find Android and iOS file.How to run?

**Comment by biill** [comment]
Hi, It's react native project, and cross platform for both Android and iOS, you can clone the whole thing

**Comment by jeffy2007** [comment]
@xuanquanzhi its a expo project, in order to get ios and android core file you may run expo eject. But beware because it cannot be undo.
