### ISSUE TITLE
Failed to compile with expo version 3.21.5

### ISSUE THREAD

**Issue by aditya61085** [biill/StackthonProject#8]
Some of your project's dependencies are not compatible with currently installed expo package version:
 - react-native-webview - expected version range: 8.1.1 - actual version installed: ^10.1.1
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
Starting Metro Bundler on port 19001. 
.
.
.
web  Failed to compile.
 web  Failed to compile.
C:/Aditya/Programming/ReactNativeStockProject/node_modules/react-native/Libraries/Components/TextInput/TextInputState.js
Module not found: Can't resolve '../../Utilities/Platform' in 'C:\Aditya\Programming\ReactNativeStockProject\node_modules\react-native\Libraries\Components\TextInput

**Comment by biill** [comment]
Did you try to npm install the specific version, my version is 3.21.3, I may build a docker image for the project, then you should not have an issue soon.
